### ISSUE TITLE
Error in running!

### ISSUE THREAD

**Issue by Benyaminteymuri** [deltazita/offline-lora#1]
Hi!

Actually I was running U're script and when I runnig this, get "usage: ./SF_allocation_global.pl terrain_file!" error.
I'm not family with Perl programming language and I don't know what is going on!

Tnx!

**Comment by deltazita** [comment]
you need to create a terrain file first with the generate_terrain script and then use it as input for the main script

e.g.: ./generate_terrain.pl 100 50 0 > test.txt
./SF_allocation_global.pl test.txt
